image: node:latest

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install http-server
    - npm install cypress --save-dev
  artifacts:
    paths:
      - node_modules/