image: node:latest

cache:
  paths:
    - node_modules/
    - dist/
  key: "$CI_BUILD_REPO"

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - build
  - deploy
  - production

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install babel-polyfill --save
  artifacts:
    paths:
      - node_modules/
      - dist/

Build_&_Testing:
  image: cypress/base:10
  stage: build
  before_script:
   - npm run clean
   - npm run clean:videos
   - npm install cypress --save
   - npm install start-server-and-test --save
   - npm install http-server --save
   - npm install babel-polyfill --save
  script:
    - npm run build
    - npm run test
  artifacts:
    paths:
      - dist/
      - node_modules/

Deployment:
  except:
    - master
  stage: deploy
  before_script:
    - npm install
    - npm install surge
    - npm install babel-polyfill
  script:
    - npm run build
    - dist/node_modules/.bin/surge
  artifacts:
    paths:
      - dist/

Master_Deployment:
  image: rambabusaravanan/firebase
  only:
    - master
  stage: production
  before_script:
    - npm install firebase-tools
    - npm install
    - npm install babel-polyfill
  script:
    - npm run build
    - firebase use --token $FIREBASE_DEPLOY_KEY restaurantmanagerclient
    - firebase deploy -m dist --token $FIREBASE_DEPLOY_KEY
  artifacts:
    paths:
      - dist/