image: node:latest

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - build
# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install http-server --save
    - npm install cypress --save
    - npm install start-server-and-test --save
    - npm install --save babel-polyfill --save
  artifacts:
    paths:
      - node_modules/

Build_&_Testing:
  stage: build
  before_script:
   - npm run clean
   - npm install http-server
   - npm install cypress
   - npm install start-server-and-test
   - npm run start:server
  script:
    - npm run compile:all
    - npx cypress run --record --key 99a23d20-0a3d-41d5-832d-0c7f88996230