image: node:latest

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - build
  - deploy
  - production-deploy

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install babel-polyfill --save
  artifacts:
    paths:
      - node_modules/

Build_&_Testing:
  image: cypress/base:10
  stage: build
  before_script:
   - npm run clean
   - npm install cypress --save
   - npm install start-server-and-test --save
   - npm install http-server --save
   - npm install babel-polyfill --save
  script:
    - npm run compile:all
    - npm run test

Deployment:
  only:
    - gitlab-ci
    - develop
  stage: deploy
  before_script:
    - npm install
    - npm install surge
    - npm install ncp

  script:
    - ncp CNAME dist/CNAME
    - node_modules/.bin/surge

Master_Deployment:
  image: rambabusaravanan/firebase
  only:
    - master
  stage: production-deploy
  before_script:
    - npm install firebase-tools
    - npm install
  script:
    - firebase use restaurantmanagerclient --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN