image: node:latest

cache:
  paths:
    - node_modules/

services:
  - cypress

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install httpserver
    - npm install cypress
  artifacts:
    paths:
      - node_modules/