image: node:latest

cache:
  paths:
    - node_modules/
    - dist/
  key: "$CI_BUILD_REPO"

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - test
  - build_deploy_develop
  - build_deploy_production

# Jobs:

Install_dependencies:
  stage: install
  script:
    - npm install
    - npm install babel-polyfill --save
  artifacts:
    paths:
      - node_modules/
      - dist/

Testing:
  image: cypress/base:10
  stage: test
  before_script:
   - npm run clean
   - npm run clean:videos
   - npm install cypress --save
   - npm install start-server-and-test --save
   - npm install http-server --save
   - npm install babel-polyfill --save
  script:
    - npm run test

Develop_Deployment:
  except:
    - master
  stage: build_deploy_develop
  before_script:
    - npm install
    - npm install surge
    - npm install babel-polyfill
  script:
    - npm run clean
    - npm run build
    - node_modules/.bin/surge dist

Production_Deployment:
  image: rambabusaravanan/firebase
  only:
    - master
  stage: build_deploy_production
  before_script:
    - npm install firebase-tools
    - npm install
    - npm install babel-polyfill
  script:
    - npm run clean
    - npm run build
    - firebase use --token $FIREBASE_DEPLOY_KEY restaurantmanagerclient
    - firebase deploy --token $FIREBASE_DEPLOY_KEY
