image: node:latest

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - test
# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install http-server --save-dev
    - npm install cypress --save-dev
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  before_script:
   - npm run clean
  script:
   - npm run test