image: node:latest

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - build
# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install http-server --save-dev
    - npm install cypress --save-dev
    - npm install start-server-and-test --save-dev
  artifacts:
    paths:
      - node_modules/

Build_&_Testing:
  stage: build
  before_script:
   - npm run clean
  script:
    - npm run compile:all
    - npm run test