image: node:latest

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - build
  - deploy

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install babel-polyfill --save
  artifacts:
    paths:
      - node_modules/

Build_&_Testing:
  image: cypress/base:10
  stage: build
  before_script:
   - npm run clean
   - npm install cypress --save
   - npm install start-server-and-test --save
   - npm install http-server --save
   - npm install babel-polyfill --save
  script:
    - npm run compile:all
    - npm run test

Deployment:
  only:
    - gitlab-ci
    - develop
  stage: deploy
  before_script:
    - npm install
    - npm install surge
    - npm install ncp

  script:
    - ncp CNAME dist/CNAME
    - node_modules/.bin/surge dist

Master_Deployment:
  only:
    - master
  stage: production
  before_script:
    - npm install
    - npm install surge
    - npm install ncp

    script:
      - ncp CNAME dist/
      - node_modules/.bin/surge dist